polls/polls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('qa/', include('qa.urls')),
    path('admin/', admin.site.urls),
]

polls/qa/urls.py
from django.urls import path

from . import views

app_name = 'qa'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/qa/models.py
from django.db import models


class Question(models.Model):
	text = models.CharField(max_length=200)
	pub_date = models.DateTimeField("Date published")

	def __str__(self) -> str:
		return self.text


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self) -> str:
		return f'{self.text} ({self.votes})'

polls/qa/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render

from qa.models import Question, Choice


def index(request):
	questions = Question.objects.all()
	return HttpResponse('<script>alert("asdf")</script>')


def detail(request, question_id):
	try:
		question = Question.objects.get(pk=question_id)
		choices = Choice.objects.filter(question_id=question.id)
	except Question.DoesNotExist:
		raise Http404("Question does not exist")
	return render(request, 'detail.html',
								{'question': question, 'choices': choices})


def results(request, question_id):
	response = f"You're looking at the results of question {question_id}."
	return HttpResponse(response)


def vote(request, question_id):
	return HttpResponse("You're voting on question %s." % question_id)

polls/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Вопрос {{ question.id }}</title>

    <style>

    </style>
</head>

<body>
    <h1>{{ question.text }}</h1>
    <ul>
        {% for choice in choices %}
            <li>{{ choice.text }}</li>
        {% endfor %}
    </ul>
</body>
</html>

polls/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Опросники</title>

    <style>
        .wrapper {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .wrapper > div {
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    <div class="wrapper">
        {% for question in questions %}
            <div>
                <a href="{% url 'qa:detail' question.id %}">{{ question.text }}</a>
                <span>({{ question.pub_date }})</span>
            </div>
        {% endfor %}
    </div>
</body>
</html>